android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.r8.maxWorkers=4

# Wild KSU manager signing (apksign plugin)
KEYSTORE_FILE=keystore/wksu.jks
KEYSTORE_PASSWORD=9d3f31e6a6e2f3f5737ec97f
KEY_ALIAS=wksu
KEY_PASSWORD=9d3f31e6a6e2f3f5737ec97f
